task 10
Adouleur/perfect-todo-app pull request #10
Opened 2024-08-27 12:14 UTC by Adouleur

Implement Clear Completed Button

2024-08-27 12:31 UTC, JisonDinAlt requested changes

2024-08-27 12:31 UTC, JisonDinAlt commented on src/constants/constants.js
> +export const filters = Object.freeze(['all', 'active', 'completed']);
Does you need Object.freeze there?

2024-08-27 14:05 UTC, KHarpushkina requested changes

2024-08-27 14:05 UTC, KHarpushkina commented on src/components/molecules/InfoBoard.vue
>      <div class="tasks-left">{{ tasksLeft }} {{ tasksLeft === 1 ? 'task' : 'tasks' }} left</div>
Could you move this calculation to the computed?

2024-09-02 09:21 UTC, Adouleur commented on src/constants/constants.js
> +export const filters = Object.freeze(['all', 'active', 'completed']);
Removed, thank you!

2024-09-02 09:21 UTC, Adouleur commented on src/components/molecules/InfoBoard.vue
>      <div class="tasks-left">{{ tasksLeft }} {{ tasksLeft === 1 ? 'task' : 'tasks' }} left</div>
Refactored, thank you!

2024-09-02 09:22 UTC, merged