Task 11/implement end to end
Adouleur/perfect-todo-app pull request #11
Opened 2024-08-29 09:25 UTC by Adouleur

Implement End-to-End (E2E) Testing with Cypress + added missing tests

2024-08-29 13:24 UTC, KHarpushkina requested changes

2024-08-29 13:24 UTC, KHarpushkina commented on src/components/atoms/ButtonComponent/ButtonComponent.spec.js
> +    const wrapper = mount(ButtonComponent);
Could you also add snapshot check. For all component test files

2024-08-29 13:24 UTC, KHarpushkina commented on src/components/molecules/InfoBoard/InfoBoard.spec.js
> +    const wrapper = mount(InfoBoard, {
You don't need to call a mount for each test, just create a const at the top of the file and then use it in all the 'it' blocks.
You can use setProps to change the properties of your component

2024-09-02 10:37 UTC, Adouleur commented on src/components/molecules/InfoBoard/InfoBoard.spec.js
> +    const wrapper = mount(InfoBoard, {
Done, thank you!

2024-09-02 10:37 UTC, Adouleur commented on src/components/atoms/ButtonComponent/ButtonComponent.spec.js
> +    const wrapper = mount(ButtonComponent);
Done! Thank you!

2024-09-02 10:37 UTC, merged